apiVersion: v1
kind: Service
metadata:
  name: redis-headless-svc
  namespace: redis-ha
  labels:
    app: redis
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - port: 6379
      name: redis
