apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: redis-ha
spec:
  serviceName: redis-sentinel
  replicas: 2
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      initContainers:
      - name: wait-for-redis
        image: redis:8.0.2
        command:
          - sh
          - -c
          - |
            until nslookup redis-0.redis-headless.redis-ha.svc.cluster.local; do
              echo "Waiting for redis-0 DNS..."
              sleep 2
            done
            until redis-cli -h redis-0 -a "$REDIS_PASSWORD" ping | grep PONG; do
              echo "Waiting for redis-0 to respond..."
              sleep 2
            done
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password
      containers:
      - name: sentinel
        image: redis:8.0.2
        command:
          - sh
          - -c
          - |
            sed -i "s|__REDIS_PASSWORD__|$REDIS_PASSWORD|g" /sentinel/sentinel.conf
            redis-server /sentinel/sentinel.conf --sentinel
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password
        ports:
          - containerPort: 26379
            name: sentinel
        volumeMounts:
          - name: sentinel-conf
            mountPath: /sentinel
      volumes:
        - name: sentinel-conf
          configMap:
            name: redis-sentinel-config
