apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-ha
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    tcp-backlog 511
    timeout 0
    appendonly yes
    appendfsync everysec
    save 900 1
    save 300 10
    save 60 10000
    dir /data
    # requirepass will be supplied via command-line in container env
