apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-ha
spec:
  serviceName: redis-headless
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:8.0.2
        command:
          - sh
          - -c
          - |
            # inject password from secret
            sed -i "s|__REDIS_PASSWORD__|$REDIS_PASSWORD|g" /redis-master/redis.conf
            redis-server /redis-master/redis.conf
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password
        ports:
          - containerPort: 6379
            name: redis
        volumeMounts:
          - name: redis-data
            mountPath: /data
          - name: redis-config
            mountPath: /redis-master
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
      volumeClaimTemplates:
        - metadata:
            name: redis-data
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: local-path
            resources:
              requests:
                storage: 10Gi
