apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: redis-ha
spec:
  serviceName: redis-sentinel-svc
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
        - name: sentinel
          image: redis:8.0.2
          command:
            - redis-server
            - /sentinel/sentinel.conf
            - --sentinel
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          ports:
            - containerPort: 26379
              name: sentinel
          volumeMounts:
            - name: sentinel-conf
              mountPath: /sentinel
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -p 26379 ping | grep -q PONG"
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -p 26379 ping | grep -q PONG"
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: sentinel-conf
          configMap:
            name: redis-sentinel-config
