apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi



kubeseal --format=yaml --cert=public-cert.pem < db-credentials.yaml > sealed-db-credentials.yaml